### ISSUE TITLE
We are experiencing a data encoding issue when working with Orca Whirlpool ProgramID.

### ISSUE THREAD

**Issue by Sagarbhalla01** [orca-so/whirlpools#130]
Hi Team,

Firstly, I want to express my gratitude for the library, which has proven to be an excellent solution for our client.

Currently, we are encountering an issue related to retrieving data from the "getProgramAccounts" function. Our team utilizes Node.js for calling this method, and while the function successfully fetches the data, the challenge lies in the fact that the data field within each account is in Buffer format.

I kindly request your prompt response and guidance on resolving this issue. Specifically, we are seeking a solution to retrieve live pools data from the "getProgramAccounts" method in a decoded format. Alternatively, if there is any other method or library available that can assist us in obtaining live data for the same purpose, we would greatly appreciate your recommendations.

Thank you in advance for your assistance.

Thanks,
Sagar Bhalla
Sr. Technical Project Manager || OODLES Technologies || India

**Comment by Sagarbhalla01** [comment]
Hello Team,

Any update on this?

**Comment by Sagarbhalla01** [comment]
Hi Team,

I haven't received the update yet.

**Comment by yugure-orca** [comment]
@Sagarbhalla01 
I think this is not issue on the SDK.
You can ask questions in Discord, please feel free to join it.
https://discord.orca.so/

For this question, you can use ParsableWhirlpool class.
https://github.com/everlastingsong/solsandbox/blob/main/orca/whirlpool/whirlpools_sdk/88a_parse_whirlpooldata_v0114.ts#L40

Thanks.
