### ISSUE TITLE
Get pool functions returns null

### ISSUE THREAD

**Issue by manavsharma136** [orca-so/whirlpools#140]
let url="https://api.mainnet-beta.solana.com";
    let whirlpoolProgramId=new PublicKey("whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc");
    const ctx = WhirlpoolContext.withProvider(connection, "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc");
    let solc_usdc= new PublicKey("7qbRF6YsyGuLUVs6Y1q64bdVrfe4ZcUUz1JRdoVNUJnm");
    let pool= await ctx.fetcher.getPool(solc_usdc);
    console.log(pool) // returns null 
facing this issue with every pool

**Comment by yugure-orca** [comment]
> const ctx = WhirlpoolContext.withProvider(connection, "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc");
second arg is just string. please use Typescript.

the type of second arg should be PublicKey, not string:
https://orca-so.github.io/whirlpools/classes/WhirlpoolContext.html#withProvider
