### ISSUE TITLE
throw new Error(`Unable to fetch Whirlpool at address at ${poolAddress}`);

### ISSUE THREAD

**Issue by DAHCROWN** [orca-so/whirlpools#160]
I'm try to implement the SDK to perform token swaps, I pass in the SPL Token mint addresses for the input and output token, so I can get the PDA and in turn use it to get the pool data, but apparently the whirlpoolPDA. I get from <code>PDAUtil.getWhirlpool</code> is not valid, and i get a <code>throw new Error(`Unable to fetch Whirlpool at address at ${poolAddress}`);</code>
![image](https://github.com/orca-so/whirlpools/assets/57120458/24e5544e-c6e1-41b5-b9b9-2e8a7ac42215)

The docs makes reference that that parameter is the <b>whirlpoolsConfigKey</b> but I believe its the whirlpools Address. 
PS: There's not other reference to what a WhirlpoolConfigKey is anywhere the Orca's docs.
The whirlpoolProgramId and ConfigAddress are <b>whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc</b> and <b>2LecshUwdy9xi7meFgHtFJQNSKk4KdTrcpvaB56dP2NQ</b>

**Comment by yugure-orca** [comment]
Please use the following endpoint to get list of whirlpools.
https://api.mainnet.orca.so/v1/whirlpool/list
