### ISSUE TITLE
Is there some configuration available which contains all the pool addresses on Whirpools?

### ISSUE THREAD

**Issue by amerfarooq** [orca-so/whirlpools#50]
The Orca TS SDK contains a [configuration file](https://github.com/orca-so/typescript-sdk/blob/main/src/public/pools/config.ts) which lists all the available markets and their addresses. Is there something similar available for Whirpools?

**Comment by odcheung** [comment]
If you already know the token pair you are looking for, you can derive the whirlpool address using the PDAUtil with the Orca constants here - https://orca-so.gitbook.io/orca-developer-portal/whirlpools/interacting-with-the-protocol/orca-whirlpools-parameters.

For the list of pools that whirlpool UI supports, you can also reference these APIs. Given that these APIs are from Orca team and not a part of the open-source whirlpool program, these APIs are subject to breaking change and may not be supported in the future. 

https://api.mainnet.orca.so/v1/whirlpool/list
https://api.mainnet.orca.so/v1/token/list

For future reference, this space is for bug reports / improvements only. You would get a quicker response for dev support if you joined us on the #whirlpool-builder channels on the orca discord!
