### ISSUE TITLE
Add a note about next.js integration

### ISSUE THREAD

**Issue by ignatevdev** [orca-so/whirlpools#518]
When trying to use typescript SDK in next.js project with a default configuration server throws an error like
"Error: ENOENT: no such file or directory, open '/Users/anton/Documents/Projects/sample/.next/server/vendor-chunks/orca_whirlpools_core_js_bindings_bg.wasm'" 

This is caused by next.js filtering out wasm bindings from server bundle, which @orca-so/whirlpools-core is trying to `require`.

One option to fix it is to mark `@orca-so/whirlpools` as an external package, which could be done by adding `serverExternalPackages: ["@orca-so/whirlpools"]` to nextConfig.

There is not much information about this problem online, so it would be useful for other people if you include this as a note in SDK docs.

**Comment by wjthieme** [comment]
I am adding an example next project here (and a bugfix which makes the wasm bundle not work in browser): https://github.com/orca-so/whirlpools/pull/530
