### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by etaques** [orca-so/whirlpools#597]
hey folks here we have an issue, "src" do not belong to that path.

![image](https://github.com/user-attachments/assets/1d6f2fab-0e13-430e-9eab-d8ed29d9a65e)

here is error line:

https://github.com/orca-so/whirlpools/blob/main/legacy-sdk/whirlpool/src/impl/whirlpool-impl.ts#L64C31-L64C37

**Comment by yugure-orca** [comment]
@etaques 
Thanks for letting us know and sorry for the inconvenience.
The issue have been resolved in https://github.com/orca-so/whirlpools/pull/598

And 0.13.12 have been released. 🙏

**Comment by yugure-orca** [comment]
@etaques 
As commented above, I believe that the issue have been resolved.
If it doesn't work well for you, please feel free to let us know.
Again, thanks for letting us know. 🙏
