### ISSUE TITLE
Impossible to harvest a single position without completely closing it.

### ISSUE THREAD

**Issue by bitjerk** [orca-so/whirlpools#86]
Hello,

https://docs.orca.so/orca-for-liquidity-providers/master#how-do-i-earn-fees-on-orca suggests that a single whirlpool position can be harvested by withdrawing "some" amount. And the withdrawing dialogue suggests the same - it promises to harvest accrued fees. However it never does that - there is only transaction for liquidity withdrawal. Even complete emptying of the position does not harvest the fees.

The fees are harvested only on burning of the position NFT.

Since re-creating the position is a somewhat costly operation (significantly costlier than adding/withdrawing the liquidity) and a quite tedious one, and harvesting all positions at once creates an accounting mess it would be great if a single position harvest functionality is restored.

**Comment by yugure-orca** [comment]
Hi @bitjerk 
AFAIK, step finance supports to harvest from a single position.

**Comment by staccDOTsol** [comment]
Hello! I understand your concern. It is true that currently, it is not possible to harvest a single position without completely closing it. The documentation you referred to may be outdated and needs to be updated. I will make sure to pass on your feedback to the Orca team. 

In the meantime, the only way to harvest the fees accrued in a position is to burn the position NFT. I understand that this can be inconvenient and costly, especially if you only want to harvest the fees from a single position. 

I suggest that you reach out to the Orca team through their official channels and let them know about your concern. They may be able to provide you with more information or a workaround.

**Comment by staccDOTsol** [comment]
Hello! I understand your concern. It is true that currently, it is not possible to harvest a single position without completely closing it. The documentation you referred to is outdated and we apologize for the confusion it may have caused. We will update the documentation to reflect the current functionality. 

To harvest the fees, you will need to burn the position NFT. We understand that this may not be the most convenient solution for some users, and we are working on improving the user experience in this regard. 

Thank you for bringing this to our attention, and please let us know if you have any further questions or concerns.

**Comment by yugure-orca** [comment]
It is technically possible to harvest from a single position without closing the position; the UI just does not support it.
